<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ReficioUpdater</AssemblyName>
    <RootNamespace>ReficioUpdater</RootNamespace>
    <Version>1.4.13.1</Version>
    <NoWarn>NU1903</NoWarn>
    <RuntimeIdentifiers>win-x64;osx-arm64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

</Project>
